# Generated by Django 5.1.1 on 2024-11-05 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descricção'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2024, 11, 20), verbose_name='Validade'),
        ),
    ]
