# Generated by Django 5.1.1 on 2024-11-07 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_orcamento_titulo_alter_orcamento_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2024, 11, 22), verbose_name='Validade'),
        ),
    ]
